apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo-app
type: Opaque
data:
  POSTGRES_USER: dG9kb191c2Vy       # base64 encoded 'todo_user'
  POSTGRES_PASSWORD: dG9kb19wYXNz    # base64 encoded 'todo_pass'
  POSTGRES_DB: dG9kb19kYg==          # base64 encoded 'todo_db'