name: Backend Docker CI

on:
  push:
    paths:
      - 'backend/**'   # Only trigger if backend folder changes
  workflow_dispatch:   # Manual trigger option

jobs:
  docker-backend:
    runs-on: ubuntu-latest
    env:
      BACKEND_IMAGE: s21aht/todo-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest
