name: Frontend Docker CI/CD

on:
  push:
    paths:
      - 'frontend/**'   # Only trigger if frontend folder changes
  workflow_dispatch:

jobs:
  docker-frontend:
    runs-on: ubuntu-latest
    env:
      FRONTEND_IMAGE: s21aht/todo-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}
            ${{ env.FRONTEND_IMAGE }}:latest

      - name: Update Kubernetes Deployment with new image
        run: |
          sed -i "s#${{ env.FRONTEND_IMAGE }}:.*#${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}#g" k8s/service/frontend-deployment.yaml
          cat k8s/service/frontend-deployment.yaml